import turtle
screen=turtle.Screen()
slow_turtle=turtle.Turtle()
slow_turtle.forward(50)
slow_turtle.right(45)
slow_turtle.forward(50)
slow_turtle.left(90)
slow_turtle.forward(50)
slow_turtle.right(45)
slow_turtle.forward(50)
slow_turtle.left(90)
slow_turtle.forward(100)
slow_turtle.right(120)
slow_turtle.forward(100)
slow_turtle.right(120)
slow_turtle.forward(100)
slow_turtle.pensize(10)
slow_turtle.color("pink")
size=(10)
for i in range(50):
    slow_turtle.circle(size)
    slow_turtle.forward(200)
    slow_turtle.right(200)
    size=size+(5)

screen.mainloop()
